# Marco Stevanella
## 101307949
### Assignment 2 - Part 2

In [52]:
import numpy as np
import pandas as pd
import sklearn


In [53]:
# import the weather.cvs file
covid = pd.read_csv('covid19.csv')
# Get Matrix of features (independent variables) as X
X = covid.iloc[:, :-1].values
# Dependent Variable Vector as y
y = covid.iloc[:, -1].values


In [54]:
# Print X and y
print(repr(X))
print(repr(y))


array([['Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'],
       ['No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes'],
       ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes'],
       ['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
       ['No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
       ['Yes', 'Yes', 'Y

In [55]:
# first let's encode the Dependent Variables, which oll of them need (YES or NOT).
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
indices = np.arange(0,8)
print(indices)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(),indices)], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[0 1 2 3 4 5 6 7]
[[0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0.

In [56]:
# Encode the Dependant Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)


[0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 0 1 0]


### Training and Testing 
#### 70 % traning 
#### 30 % Test

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

In [58]:
# Training X
# 19 rows -> 70% taken randomly from the dataset
print(X_train)


[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]]


In [59]:
# Testing y
# 11 rows -> 30% taken randomly from the dataset
print(X_test)


[[1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0.]]


In [60]:
# 19 self-assessments -> 1 = No, 0 = Yes
# These decisions are based on the X_train data set
print(y_train)


[0 1 0 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0]


In [61]:
# 9 observations -> 1 = TRUE, 0 = FALSE
# These decisions are based on the X_train data set
print(y_test)


[0 1 0 0 1 1 1 1 1]


In [62]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()


In [63]:
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)




In [64]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))


1.0
