# Marco Stevanella
## 101307949
### Assignment 2 - Part 1

In [153]:
import numpy as np
import pandas as pd
import sklearn

In [154]:
# import the weather.cvs file
weather = pd.read_csv('weather.csv')
# Get Matrix of features (independent variables) as X
X = weather.iloc[: , :-1].values
# Dependent Variable Vector as y
y = weather.iloc[:, -1].values


In [155]:
# Print X and y 
print(repr(X))
print(repr(y))

array([[10, 0.0, 0, 0.0, 0, 2, 1, 20, 4, 'good'],
       [5, 1.0, 40, 0.0, 0, 1, 0, 70, 6, 'good'],
       [5, 2.5, 80, 0.0, 0, 1, 0, 80, 6, 'quite good'],
       [7, 0.0, 0, 0.0, 0, 11, 3, 50, 4, 'good'],
       [15, 0.0, 0, 0.0, 0, 20, 5, 40, 4, 'good'],
       [10, 0.0, 0, 0.0, 0, 0, 0, 80, 6, 'not good'],
       [7, 0.0, 0, 0.0, 0, 0, 0, 80, 6, 'not good'],
       [5, 0.0, 0, 0.0, 0, 11, 2, 60, 4, 'good'],
       [4, 0.0, 0, 0.0, 0, 2, 2, 40, 3, 'good'],
       [1, 0.1, 30, 0.0, 0, 2, 2, 40, 3, 'good'],
       [3, 3.5, 50, 0.0, 0, 2, 0, 80, 6, 'good'],
       [-2, 0.0, 0, 0.5, 30, 2, 0, 80, 3, 'quite good'],
       [-4, 0.0, 0, 1.5, 70, 4, 0, 80, 2, 'not good'],
       [-6, 0.0, 0, 1.5, 50, 8, 0, 80, 2, 'not good'],
       [0, 0.0, 0, 0.5, 20, 3, 0, 80, 1, 'quite good'],
       [-15, 0.0, 0, 0.0, 0, 17, 5, 50, 1, 'quite good'],
       [-10, 0.0, 0, 0.0, 0, 15, 4, 40, 1, 'quite good'],
       [20, 0.0, 0, 0.0, 0, 2, 4, 40, 2, 'quite good'],
       [25, 10.0, 70, 0.0, 0, 4, 0, 80, 5,

### What if we have some missing data?
#### As I made this data set, I know there in not missing data... but this could not always be the case!

In [156]:
# using sklearn we can handle missing data
from sklearn.impute import SimpleImputer
# create an instance of this class, and specify to replace missing data with the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# fit method will interface the imputer to the Matrix of Features X
imputer.fit(X[:,:9])
# transform will apply the changes
X[:,:9] = imputer.transform(X[:,:9])

In [157]:
# Check update X
print(X)

[[10.0 0.0 0.0 0.0 0.0 2.0 1.0 20.0 4.0 'good']
 [5.0 1.0 40.0 0.0 0.0 1.0 0.0 70.0 6.0 'good']
 [5.0 2.5 80.0 0.0 0.0 1.0 0.0 80.0 6.0 'quite good']
 [7.0 0.0 0.0 0.0 0.0 11.0 3.0 50.0 4.0 'good']
 [15.0 0.0 0.0 0.0 0.0 20.0 5.0 40.0 4.0 'good']
 [10.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 6.0 'not good']
 [7.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 6.0 'not good']
 [5.0 0.0 0.0 0.0 0.0 11.0 2.0 60.0 4.0 'good']
 [4.0 0.0 0.0 0.0 0.0 2.0 2.0 40.0 3.0 'good']
 [1.0 0.1 30.0 0.0 0.0 2.0 2.0 40.0 3.0 'good']
 [3.0 3.5 50.0 0.0 0.0 2.0 0.0 80.0 6.0 'good']
 [-2.0 0.0 0.0 0.5 30.0 2.0 0.0 80.0 3.0 'quite good']
 [-4.0 0.0 0.0 1.5 70.0 4.0 0.0 80.0 2.0 'not good']
 [-6.0 0.0 0.0 1.5 50.0 8.0 0.0 80.0 2.0 'not good']
 [0.0 0.0 0.0 0.5 20.0 3.0 0.0 80.0 1.0 'quite good']
 [-15.0 0.0 0.0 0.0 0.0 17.0 5.0 50.0 1.0 'quite good']
 [-10.0 0.0 0.0 0.0 0.0 15.0 4.0 40.0 1.0 'quite good']
 [20.0 0.0 0.0 0.0 0.0 2.0 4.0 40.0 2.0 'quite good']
 [25.0 10.0 70.0 0.0 0.0 4.0 0.0 80.0 5.0 'not good']
 [30.0 0.0 0.0 0.0 0.0 2

### Encoding the categorical data
#### In our case the 'visibility' column has categorical data. Categorical data is represented by a string, and it usually repeats the same string. In the case of visibility is 'good', 'quite good' and 'not good'. We will use what is called 'one hot encoding' to split this column into sub-columns representing the repeated values. The one hot encoding will create binary vectors for each of the repeated values. This is done to avoid numerical order, that could potentially misinterpret the integrity of the column.


In [158]:
# first let's encode the Dependent Variable 'visibility'
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='drop')
X_visibility_enc = np.array(ct.fit_transform(X))
X_visibility_enc



array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [159]:
# To keep the column in the same position
X = np.delete(X, np.s_[-1], axis=1)
X = np.hstack((X,X_visibility_enc))
print(X)


[[10.0 0.0 0.0 0.0 0.0 2.0 1.0 20.0 4.0 1.0 0.0 0.0]
 [5.0 1.0 40.0 0.0 0.0 1.0 0.0 70.0 6.0 1.0 0.0 0.0]
 [5.0 2.5 80.0 0.0 0.0 1.0 0.0 80.0 6.0 0.0 0.0 1.0]
 [7.0 0.0 0.0 0.0 0.0 11.0 3.0 50.0 4.0 1.0 0.0 0.0]
 [15.0 0.0 0.0 0.0 0.0 20.0 5.0 40.0 4.0 1.0 0.0 0.0]
 [10.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 6.0 0.0 1.0 0.0]
 [7.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 6.0 0.0 1.0 0.0]
 [5.0 0.0 0.0 0.0 0.0 11.0 2.0 60.0 4.0 1.0 0.0 0.0]
 [4.0 0.0 0.0 0.0 0.0 2.0 2.0 40.0 3.0 1.0 0.0 0.0]
 [1.0 0.1 30.0 0.0 0.0 2.0 2.0 40.0 3.0 1.0 0.0 0.0]
 [3.0 3.5 50.0 0.0 0.0 2.0 0.0 80.0 6.0 1.0 0.0 0.0]
 [-2.0 0.0 0.0 0.5 30.0 2.0 0.0 80.0 3.0 0.0 0.0 1.0]
 [-4.0 0.0 0.0 1.5 70.0 4.0 0.0 80.0 2.0 0.0 1.0 0.0]
 [-6.0 0.0 0.0 1.5 50.0 8.0 0.0 80.0 2.0 0.0 1.0 0.0]
 [0.0 0.0 0.0 0.5 20.0 3.0 0.0 80.0 1.0 0.0 0.0 1.0]
 [-15.0 0.0 0.0 0.0 0.0 17.0 5.0 50.0 1.0 0.0 0.0 1.0]
 [-10.0 0.0 0.0 0.0 0.0 15.0 4.0 40.0 1.0 0.0 0.0 1.0]
 [20.0 0.0 0.0 0.0 0.0 2.0 4.0 40.0 2.0 0.0 0.0 1.0]
 [25.0 10.0 70.0 0.0 0.0 4.0 0.0 80.0 5.

In [160]:
# Encode the Dependant Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1]


### Training and Testing 
#### 80 % trining 
#### 20 % Test

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [162]:
# Training X
# 25 rows -> 80% taken randomly from the dataset
print(X_train)


[[10.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 6.0 0.0 1.0 0.0]
 [7.0 0.0 0.0 0.0 0.0 11.0 3.0 50.0 4.0 1.0 0.0 0.0]
 [40.0 0.0 0.0 0.0 0.0 0.0 9.0 50.0 6.0 1.0 0.0 0.0]
 [20.0 0.0 0.0 0.0 0.0 2.0 4.0 40.0 2.0 0.0 0.0 1.0]
 [3.0 3.5 50.0 0.0 0.0 2.0 0.0 80.0 6.0 1.0 0.0 0.0]
 [35.0 0.0 0.0 0.0 0.0 2.0 11.0 78.0 6.0 1.0 0.0 0.0]
 [-10.0 0.0 0.0 0.0 0.0 15.0 4.0 40.0 1.0 0.0 0.0 1.0]
 [15.0 0.0 0.0 0.0 0.0 20.0 5.0 40.0 4.0 1.0 0.0 0.0]
 [17.0 0.0 0.0 0.0 0.0 6.0 5.0 50.0 2.0 1.0 0.0 0.0]
 [1.0 0.1 30.0 0.0 0.0 2.0 2.0 40.0 3.0 1.0 0.0 0.0]
 [0.0 0.0 0.0 0.5 20.0 3.0 0.0 80.0 1.0 0.0 0.0 1.0]
 [5.0 0.0 0.0 0.0 0.0 11.0 2.0 60.0 4.0 1.0 0.0 0.0]
 [-1.0 0.0 0.0 1.0 30.0 2.0 1.0 25.0 2.0 1.0 0.0 0.0]
 [-6.0 0.0 0.0 1.5 50.0 8.0 0.0 80.0 2.0 0.0 1.0 0.0]
 [-10.0 0.0 0.0 0.0 0.0 1.0 6.0 24.0 1.0 1.0 0.0 0.0]
 [37.0 0.0 0.0 0.0 0.0 2.0 10.0 60.0 6.0 1.0 0.0 0.0]
 [45.0 0.0 0.0 0.0 0.0 0.0 10.0 55.0 7.0 1.0 0.0 0.0]
 [30.0 0.0 0.0 0.0 0.0 2.0 10.0 67.0 5.0 1.0 0.0 0.0]
 [-2.0 0.0 0.0 0.5 30.0 2.0 0.0 80.0

In [163]:
# Testing y
# 7 rows -> 20% taken randomly from the dataset
print(X_test)


[[15.0 2.5 70.0 0.0 0.0 10.0 0.0 70.0 5.0 1.0 0.0 0.0]
 [5.0 1.0 40.0 0.0 0.0 1.0 0.0 70.0 6.0 1.0 0.0 0.0]
 [24.0 0.1 56.0 0.0 0.0 4.0 1.0 70.0 5.0 1.0 0.0 0.0]
 [7.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 6.0 0.0 1.0 0.0]
 [-15.0 0.0 0.0 0.0 0.0 17.0 5.0 50.0 1.0 0.0 0.0 1.0]
 [5.0 2.5 80.0 0.0 0.0 1.0 0.0 80.0 6.0 0.0 0.0 1.0]
 [-4.0 0.0 0.0 1.5 70.0 4.0 0.0 80.0 2.0 0.0 1.0 0.0]]


In [164]:
# 25 playable days -> 1 = TRUE, 0 = FALSE
# These decisions are based on the X_train data set
print(y_train)


[1 1 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1]


In [165]:
# 7 playable days -> 1 = TRUE, 0 = FALSE
# These decisions are based on the X_train data set
print(y_test)


[0 1 1 1 0 0 0]


#### Future Scaling 
prevent a feature to prevent in another 

![image](future_scaling.png)


In [166]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:9] = sc.fit_transform(X_train[:,:9])
X_test[:,:9] = sc.transform(X_test[:,:9])

In [167]:
print(X_train)


[[-0.18134471605279398 -0.28532500632654095 -0.41323881687583786
  -0.38769414293519794 -0.40986832972763065 -0.8544778817097172
  -1.118033988749895 1.3482929269675192 1.3251783128981587 0.0 1.0 0.0]
 [-0.3756426261093589 -0.28532500632654095 -0.41323881687583786
  -0.38769414293519794 -0.40986832972763065 1.3834403799109705
  -0.2795084971874737 -0.21948954625052655 0.22086305214969307 1.0 0.0
  0.0]
 [1.7616343845128553 -0.28532500632654095 -0.41323881687583786
  -0.38769414293519794 -0.40986832972763065 -0.8544778817097172
  1.3975424859373686 -0.21948954625052655 1.3251783128981587 1.0 0.0 0.0]
 [0.46631498413575573 -0.28532500632654095 -0.41323881687583786
  -0.38769414293519794 -0.40986832972763065 -0.44758365232413755 0.0
  -0.7420837039898751 -0.8834522085987726 0.0 0.0 1.0]
 [-0.6347065061847788 1.4246707507674545 2.3054376099388847
  -0.38769414293519794 -0.40986832972763065 -0.44758365232413755
  -1.118033988749895 1.3482929269675192 1.3251783128981587 1.0 0.0 0.0]
 [1.4378

In [168]:
print(X_test)


[[0.1424851340414809 0.9361005344548844 3.392908180664774
  -0.38769414293519794 -0.40986832972763065 1.1799932652181808
  -1.118033988749895 0.8256987692281706 0.7730206825239259 1.0 0.0 0.0]
 [-0.5051745661470688 0.2032452099860292 1.7617023245759402
  -0.38769414293519794 -0.40986832972763065 -0.6510307670169273
  -1.118033988749895 0.8256987692281706 1.3251783128981587 1.0 0.0 0.0]
 [0.7253788642111756 -0.23646798469528396 2.6316787811566513
  -0.38769414293519794 -0.40986832972763065 -0.04068942293855799
  -0.8385254915624212 0.8256987692281706 0.7730206825239259 1.0 0.0 0.0]
 [-0.3756426261093589 -0.28532500632654095 -0.41323881687583786
  -0.38769414293519794 -0.40986832972763065 -0.8544778817097172
  -1.118033988749895 1.3482929269675192 1.3251783128981587 0.0 1.0 0.0]
 [-1.8004939665241684 -0.28532500632654095 -0.41323881687583786
  -0.38769414293519794 -0.40986832972763065 2.604123068067709
  0.2795084971874737 -0.21948954625052655 -1.4356098389730054 0.0 0.0 1.0]
 [-0.505174

In [169]:
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [170]:
predictions = classifier.predict(X_test)
print(predictions)
print(y_test)

[0 1 1 1 1 0 0]
[0 1 1 1 0 0 0]


In [171]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.8571428571428571


In [172]:
columns = np.array(weather.columns.values)
features = columns[:-2]
extra_columns = ["good","quite good","not good"]
features = np.concatenate((features, extra_columns))
print(features)
options = np.array(["TRUE","FALSE"])
print(options)


['temperatures' 'rain' 'rain_duration' 'snow' 'snow_duration' 'wind' 'uv'
 'humidity' 'air_quality' 'good' 'quite good' 'not good']
['TRUE' 'FALSE']


In [173]:
import pydotplus

dot_data = tree.export_graphviz(
 classifier,
 out_file=None,
 feature_names=features,
 class_names=options,
 filled=True,
 rounded=True,
 special_characters=True
)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("tennis_predict.pdf")

True